spring:
  # DB
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:~/jerryshop
    driverClassName: org.h2.Driver
    username: jerryshop
    password: 
    
  # JPA
  jpa:
    properties:
      hibernate:
        dialect:
          org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update